name: photos_repository
description: Repository providing photos
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
